const palette = {
  bg: "#131416",
  surface: "#18181B",
  surface2: "#222226",
  tagSurface: "#222226",
  surfaceTransparent: "rgba(255,255,255,0.04)",
  textPrimary: "#ffffff",
  textMuted: "#9b9b9b",
  accent: "#4459ff",
  green: "#baf24a",
  greenSoft: "rgba(186,242,74,0.15)",
  red: "#ff7584",
  redSoft: "rgba(255,117,132,0.15)",
  bitcoin: "#f7931a",
  nbaBlue: "#1e58cd",
  nbaBlueSoft: "#6095ff",
  nbaOrange: "#f05210",
  doosanRed: "#bc0014",
  liveOrange: "#ff5c16",
  liveYellow: "#facc15",
  spainRed: "#c8102e",
  spainYellow: "#ffc400",
};

const colors = {
  light: {
    text: palette.textPrimary,
    tint: palette.accent,
    background: palette.bg,
    foreground: palette.textPrimary,
    card: palette.surface,
    cardForeground: palette.textPrimary,
    primary: palette.accent,
    primaryForeground: palette.textPrimary,
    secondary: palette.surface2,
    secondaryForeground: palette.textPrimary,
    muted: palette.surface2,
    mutedForeground: palette.textMuted,
    accent: palette.accent,
    accentForeground: palette.textPrimary,
    destructive: palette.red,
    destructiveForeground: palette.textPrimary,
    border: palette.surface2,
    input: palette.surface2,
    bg: palette.bg,
    surface: palette.surface,
    surface2: palette.surface2,
    tagSurface: palette.tagSurface,
    surfaceTransparent: palette.surfaceTransparent,
    textPrimary: palette.textPrimary,
    textMuted: palette.textMuted,
     // Light-mode semantic colors from the attached reference swatches.
     green: "#527941",
     greenSoft: "#EDF2EB",
     red: "#BA4247",
     redSoft: "#F7EBEC",
    bitcoin: palette.bitcoin,
    nbaBlue: palette.nbaBlue,
    nbaBlueSoft: palette.nbaBlueSoft,
    nbaOrange: palette.nbaOrange,
    doosanRed: palette.doosanRed,
    liveOrange: palette.liveOrange,
    liveYellow: palette.liveYellow,
    spainRed: palette.spainRed,
    spainYellow: palette.spainYellow,
  },
  radius: 12,
};

export default colors;
