kind = "mobile"
previewPath = "/"
title = "Predict Mobile"
version = "1.0.0"
id = "artifacts/predict-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 23880

[services.development]
run = "pnpm --filter @workspace/predict-mobile run start"

[services.production]
build = [ "pnpm", "--filter", "@workspace/predict-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/predict-mobile", "run", "serve" ]

[services.env]
PORT = "23880"
BASE_PATH = "/"
